---
# IP adresses must be the ones once the installation on site has been done
raspberry_with_camera:
  hosts:
    rasp2:
      ansible_host: raspcamera1.local
      ansible_user: pi
      ansible_password: raspberry
      ansible_python_interpreter: python3
