---
# install core repositories

- name: Clone pyro-engine
  ansible.builtin.git:
    repo: "https://github.com/pyronear/pyro-engine.git"
    dest: /home/pi/pyro-engine
    version: master
  register: pyroengine_output
  until: not pyroengine_output.failed
  retries: 3
  delay: 10
  tags: pyro_engine

- name: Update text file with new hash of the pyro-engine repository
  ansible.builtin.copy:
    dest: /home/pi/pyroengine_version.txt
    content: "{{ pyroengine_output.after }}"
  tags: pyro_engine

- name: install rpi main requirements from pyro-engine and create virtual env
  pip:
    requirements: /home/pi/pyro-engine/main.rpi.requirements.txt
    virtualenv: /home/pi/pyro-engine/venv
    virtualenv_command: python3 -m venv
  tags: pyro_engine
