---
- name: update main raspberries
  hosts: localhost
  connection: local

  tasks:
    - name: Clone pyro-engine
      ansible.builtin.git:
        repo: "https://github.com/pyronear/pyro-engine.git"
        dest: /home/pi/pyro-engine
        version: master
      register: pyroengine_output
      until: not pyroengine_output.failed
      retries: 5
      delay: 10
      tags: pyro_engine_update

    - name: update rpi main requirements from pyro-engine
      pip:
        requirements: /home/pi/pyro-engine/main.rpi.requirements.txt
        virtualenv: /home/pi/pyro-engine/venv
      register: requirements_output
      until: not requirements_output.failed
      retries: 5
      delay: 10
      tags: pyro_engine_update

    - name: re-build the image docker-composer.yml and relaunch it
      ansible.builtin.shell:
        cmd: docker-compose up -d --build
        chdir: /home/pi/pyro-engine/server
      environment:
        PORT: 8002
      become: true
      tags: pyro_engine_update

    - name: Update text file with new hash of the pyro-engine repository
      ansible.builtin.copy:
        dest: /home/pi/pyroengine_version.txt
        content: "{{ pyroengine_output.after }}"
      tags: pyro_engine_update
