---
- name: update camera rpi from main rpi
  hosts: raspberry_with_camera

  tasks:
    - name: copy pi_utils folder from pyroengine to be executed later on hosts
      ansible.builtin.copy:
        src: /home/pi/pyro-engine/pyroengine/pi_utils/
        dest: /home/pi/python_scripts
      tags: python_scripts_camera
