---
# tasks file for rpi_camera_config
- name: enable RPI camera usage
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: '^#?gpu_mem', line: 'gpu_mem=512'}
    - {regexp: '^#?disable_camera_led', line: 'disable_camera_led=1'}
    - {regexp: '^#?start_file', line: 'start_file=start4x.elf'}
    - {regexp: '^#?fixup_file', line: 'fixup_file=fixup4x.dat'}
    - {regexp: '^#?start_x', line: 'start_x=1'}
  become: true
  register: camera_output
  tags: test

- name: reboot of RPI after camera enabling
  reboot:
  when: camera_output.changed
  become: true
  tags: test
