---
- name: raspberry common config
  hosts: raspberry

  tasks:
    - name: install python3
      raw: test -r /usr/bin/python3 || (apt-get update && apt-get install -y python3)
      tags: common_config

    - name: install git, pip3 and python3-venv
      apt:
        name:
          - git
          - python3-pip
          - python3-venv
        state: latest
        update_cache: true
      become: true
      register: apt_output
      tags: common_config

    - name: full upgrade of all packages
      apt:
        upgrade: full
      become: true
      when: apt_output.changed
      tags: dangerous

    - name: reboot of RPI
      reboot:
      when: apt_output.changed
      become: true
      tags: dangerous
