---
- name: local-api dependecies and build
  hosts: raspberry_masters

  roles:
    - role: geerlingguy.docker_arm
      become: true
      tags: docker_installation

  tasks:
    - name: create .env file for main rpi (needed for monitor_pi.py)
      ansible.builtin.copy:
        dest: /home/pi/pyro-engine/pyroengine/pi_utils/.env
        content: |
          MAIN_RPI_IP=127.0.0.1
          MAIN_RPI_WEBSERVER_PORT=8002

    - name: run docker-composer.yml (takes around 10 to 15 minutes)
      ansible.builtin.shell:
        cmd: docker-compose up -d --build
        chdir: /home/pi/pyro-engine/server
      environment:
        PORT: 8002
      become: true
      tags: local_api
