---
- name: pyro-vision dependecies
  hosts: raspberry_masters

  pre_tasks:
    - name: install dependecies needed for pyro-vision module
      apt:
        name:
          - libopenblas-dev
          - libopenjp2-7
          - libtiff5
        state: latest
        update_cache: true
      become: true
      register: apt_output
      tags: always

    - name: install pytorch & create venv
      pip:
        name: https://github.com/pyronear/pyro-vision/releases/download/v0.1.1/torch-1.7.0a0-cp37-cp37m-linux_armv7l.whl
        virtualenv: /home/pi/python_scripts/venv
        virtualenv_command: python3 -m venv
      tags: always

    - name: install torchvision
      pip:
        name: https://github.com/pyronear/pyro-vision/releases/download/v0.1.1/torchvision-0.8.0-cp37-cp37m-linux_armv7l.whl
        virtualenv: /home/pi/python_scripts/venv
      tags: always
