---
- name: raspberry with camera config
  hosts: raspberry_with_camera

  tasks:
    - name: copy camera.rpi.requirements.txt
      ansible.builtin.copy:
        src: ../camera.rpi.requirements.txt
        dest: /home/pi/python_scripts/camera.rpi.requirements.txt
      tags: python_script

    - name: copy .env file
      ansible.builtin.copy:
        src: ../.env
        dest: /home/pi/python_scripts/.env
      tags: python_script

    - name: copy python scripts from scripts_camera_rpi to be executed later on hosts
      ansible.builtin.copy:
        src: ../scripts_camera_rpi/
        dest: /home/pi/python_scripts
      tags: python_script

    - name: install camera.rpi.requirements.txt & create venv
      pip:
        requirements: /home/pi/python_scripts/camera.rpi.requirements.txt
        virtualenv: /home/pi/python_scripts/venv
        virtualenv_command: python3 -m venv
      tags: python_script

    - name: run script take_picture.py
      ansible.builtin.command:
        cmd: /home/pi/python_scripts/venv/bin/python3 take_picture.py
        chdir: /home/pi/python_scripts/
      tags: python_script
