---
- name: setup nginx reverse proxy in order to let pi camera metrics available via VPN
  hosts: raspberry_mains

  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
        update_cache: true
      become: true

    - name: create nginx.conf from template 
      ansible.builtin.template:
        src: ../templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      become: true

    - name: add buffer.conf from template 
      ansible.builtin.template:
        src: ../templates/buffer.conf.j2
        dest: /etc/nginx/buffer.conf
      become: true

    - name: add common_location.conf from template 
      ansible.builtin.template:
        src: ../templates/common_location.conf.j2
        dest: /etc/nginx/common_location.conf
      become: true

    - name: add common.conf from template 
      ansible.builtin.template:
        src: ../templates/common.conf.j2
        dest: /etc/nginx/common.conf
      become: true

    - name: start and enable service
      ansible.builtin.systemd:
        name: nginx
        state: started
        daemon_reload: yes
        enabled: yes
      become: true
