---
- name: stop service
  hosts: raspberry_masters

  tasks:
    - name: stop service
      ansible.builtin.service:
        name: "{{ service }}"
        state: stopped
      become: true
      tags: stop
