---
# tasks file for ssh_role
- name: Set authorized key on rpi taken from local file
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', public_key_path) }}"

- name: Generated ssh key on rpi
  openssh_keypair:
    path: ~/.ssh/id_rsa
    type: rsa

- name: fetch rpi public key to copy it on local host
  ansible.builtin.fetch:
    src: ~/.ssh/id_rsa.pub
    dest: ./ssh_rpi_keys/id_rsa_{{ inventory_hostname }}.pub
    flat: true

- name: list file in directory
  ansible.builtin.find:
    paths: ./ssh_rpi_keys
  register: files_list
  delegate_to: 127.0.0.1

- name: set authorized_keys on rpi
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', item.path ) }}"
  with_items: "{{ files_list.files }}"
