---
# tasks file for ssh_role
- name: Wait 900 seconds for target connection to become reachable/usable
  wait_for_connection:
    timeout: 900
    sleep: 5

- name: create .ssh directory
  ansible.builtin.file:
    path: ~/.ssh/
    state: directory

- name: Set authorized key on rpi taken from localhost file
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', public_key_path) }}"

- name: list file in directory
  ansible.builtin.find:
    paths: ../files/ssh_localhost_keys
  register: files_list
  delegate_to: 127.0.0.1

- name: Set multiple authorized_keys on all rpi from folder files/ssh_localhost_keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', item.path ) }}"
  with_items: "{{ files_list.files }}"

- name: Generated ssh key on rpi
  openssh_keypair:
    path: ~/.ssh/id_rsa
    type: rsa

- name: fetch rpi public key to copy it on local host
  ansible.builtin.fetch:
    src: ~/.ssh/id_rsa.pub
    dest: ../files/ssh_rpi_keys/id_rsa_{{ inventory_hostname }}.pub
    flat: true

- name: fetch rpi ecdsa key to copy it on local host
  ansible.builtin.fetch:
    src: /etc/ssh/ssh_host_ecdsa_key.pub
    dest: ../files/ssh_ecdsa_keys/ssh_host_ecdsa_key_{{ inventory_hostname }}.pub
    flat: true

- name: list file in directory
  ansible.builtin.find:
    paths: ../files/ssh_rpi_keys
  register: files_list
  delegate_to: 127.0.0.1

- name: set authorized_keys on all rpi
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', item.path ) }}"
  with_items: "{{ files_list.files }}"

- name: set known_hosts on all rpi using id address
  ansible.builtin.known_hosts:
    name: "{{ item.value.ansible_host }}"
    state: present
    key: >
      {{ item.value.ansible_host }}
      {{ lookup('file', '../files/ssh_ecdsa_keys/ssh_host_ecdsa_key_' + item.key + '.pub' ) }}
  loop: "{{ hostvars | dict2items }}"

- name: set known_hosts on all rpi with hostname dns
  ansible.builtin.known_hosts:
    name: "{{ item.value.hostname }}.local"
    state: present
    key: >
      {{ item.value.hostname }}.local
      {{ lookup('file', '../files/ssh_ecdsa_keys/ssh_host_ecdsa_key_' + item.key + '.pub' ) }}
  loop: "{{ hostvars | dict2items }}"
